FROM openjdk:11
ADD ./target/ontology-management-service-0.0.1-SNAPSHOT /usr/src/ontology-management-service-0.0.1-SNAPSHOT
EXPOSE 8089
WORKDIR usr/src
ENTRYPOINT ["java","-jar","ontology-management-service-0.0.1-SNAPSHOT"]

